source:
  ros__parameters:
    msg_period: 500.0 #ms
    scan_width: 3140 # used in pc2 and laserscan
    scan_height: 100 # only in pc2
    use_smart_pointer: true

sink:
  ros__parameters:
    file_output_prefix: "output/latency_ls_inter_fake"
    rolling_window_size: 20
    long_mode: false
    long_mode_total_groups: 20
    long_mode_period: 1800 # [seconds] between two group


/**:
  ros__parameters:
    msg_type: 1
    # 0 = laserscan
    # 1 = pointcloud    